comment
nulzo/DiscordBot pull request #81
Opened 2023-08-18 01:24 UTC by ethanlchristensen

2023-09-01 18:41 UTC, nulzo commented
@ethanlchristensen why are there conflicts

2023-09-01 18:42 UTC, nulzo requested changes
fix conflicts

2023-09-02 16:26 UTC, ethanlchristensen commented
Sure thing

2023-09-09 00:45 UTC, ethanlchristensen commented
@nulzo kindly fixed conflicts

2023-09-09 00:56 UTC, Mr-Oregano requested changes, later dismissed

2023-09-09 00:56 UTC, Mr-Oregano commented on BOT/_slash/marcus_says.py
> +        # args is passed in from slash_master. slash_master recieved args
Args isn't capitalized! ☝️ 🤓

2023-09-09 17:02 UTC, ethanlchristensen commented on BOT/_slash/marcus_says.py
> +        # args is passed in from slash_master. slash_master recieved args
It shouldn't be @Mr-Oregano

2023-09-09 17:43 UTC, nulzo approved these changes

2023-09-09 17:43 UTC, merged